-- Criação da tabela AGENTE_COMUNITARIO

CREATE TABLE AGENTE_COMUNITARIO (
    ACS_ID SERIAL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    SENHA BYTEA NOT NULL,
    ENDERECO VARCHAR(255) NOT NULL,
    CEP VARCHAR(10) NOT NULL,
    AREA TEXT NOT NULL,
    MICRO_AREA INTEGER NOT NULL
);
